name: py-llmfh
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _anaconda_depends=2022.10
  - alabaster=0.7.12
  - anaconda=custom
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - asttokens=2.0.5
  - atomicwrites=1.4.0
  - automat=20.2.0
  - autopep8=1.6.0
  - backcall=0.2.0
  - backports=1.1
  - binaryornot=0.4.4
  - blas=1.0
  - bleach=4.1.0
  - blosc=1.21.3
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.0
  - ca-certificates=2023.5.7
  - certifi=2023.5.7
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - cookiecutter=1.7.3
  - cssselect=1.1.0
  - curl=7.88.1
  - cycler=0.11.0
  - dal=2021.4.0
  - dask-core=2023.4.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - diff-match-patch=20200713
  - et_xmlfile=1.1.0
  - executing=0.8.3
  - ffmpeg=4.2.2
  - fonttools=4.25.0
  - freetype=2.12.1
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.76.2
  - glib-tools=2.76.2
  - gmp=6.2.1
  - gnutls=3.6.15
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - hdf5=1.10.6
  - heapdict=1.0.1
  - hyperlink=21.0.0
  - icu=70.1
  - importlib_metadata=6.0.0
  - incremental=21.3.0
  - iniconfig=1.1.1
  - intel-openmp=2021.4.0
  - intervaltree=3.1.0
  - ipython_genutils=0.2.0
  - isort=5.9.3
  - itemadapter=0.3.0
  - itemloaders=1.0.4
  - itsdangerous=2.0.1
  - jaraco.classes=3.2.1
  - jdcal=1.4.1
  - jellyfish=2.2.10
  - jemalloc=4.5.0
  - jinja2-time=0.2.0
  - jmespath=0.10.0
  - jpeg=9e
  - jq=1.5
  - json5=0.9.6
  - jupyter_client=8.1.0
  - jupyter_console=6.6.3
  - jupyter_core=5.3.0
  - jupyter_server=1.23.4
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.22.0
  - jupyterlab_widgets=3.0.5
  - jxrlib=1.1
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - lerc=3.0
  - libaec=1.0.4
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=13.0.1
  - libcurl=7.88.1
  - libcxx=16.0.3
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.4.4
  - libgcc=4.8.5
  - libgfortran=3.0.1
  - libglib=2.76.2
  - libiconv=1.17
  - libidn2=2.3.2
  - libllvm11=11.1.0
  - libllvm12=12.0.0
  - libllvm13=13.0.1
  - libnghttp2=1.52.0
  - libogg=1.3.5
  - libopenblas=0.3.20
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.3
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libsqlite=3.42.0
  - libssh2=1.10.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libvorbis=1.3.7
  - libvpx=1.7.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.10.3
  - libxslt=1.1.37
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - lzo=2.10
  - matplotlib-base=3.7.1
  - mccabe=0.7.0
  - mkl=2021.4.0
  - mock=4.0.3
  - more-itertools=8.12.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpi=1.0
  - mpich=3.3.2
  - msgpack-python=1.0.3
  - munkres=1.0.7
  - mypy_extensions=0.4.3
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - ncurses=6.4
  - nettle=3.7.3
  - nltk=3.7
  - nomkl=3.0
  - nose=1.3.7
  - nspr=4.35
  - nss=3.89
  - numpy-base=1.22.3
  - olefile=0.46
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.1.0
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.2.0
  - pcre=8.45
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - poyo=0.5.0
  - prometheus_client=0.14.1
  - prompt_toolkit=3.0.36
  - protego=0.1.16
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py=1.11.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pyls-spyder=0.4.0
  - pyqt=5.15.7
  - pytables=3.7.0
  - python=3.10.11
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-lmdb=1.4.1
  - python-lsp-jsonrpc=1.0.0
  - python-slugify=5.0.2
  - python.app=3
  - python_abi=3.10
  - pyviz_comms=2.0.2
  - qdarkstyle=3.0.2
  - qt=5.15.8
  - qt-main=5.15.8
  - qt-webengine=5.15.8
  - qtwebkit=5.212
  - readline=8.2
  - requests-file=1.5.1
  - ruamel.yaml.clib=0.2.6
  - ruamel_yaml=0.17.21
  - send2trash=1.8.0
  - service_identity=18.1.0
  - six=1.16.0
  - smart_open=5.2.1
  - snappy=1.1.9
  - snowballstemmer=2.2.0
  - sortedcollections=2.1.0
  - sortedcontainers=2.4.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tbb4py=2021.8.0
  - tblib=1.7.0
  - text-unidecode=1.3
  - textdistance=4.2.1
  - threadpoolctl=2.2.0
  - three-merge=0.1.1
  - tifffile=2021.7.2
  - time=1.8
  - tk=8.6.12
  - tldextract=3.2.0
  - toml=0.10.2
  - typing_extensions=4.5.0
  - tzdata=2023c
  - unidecode=1.2.0
  - unixodbc=2.3.11
  - w3lib=1.21.0
  - wcwidth=0.2.5
  - wget=1.20.3
  - x264=1!157.20191217
  - xlrd=2.0.1
  - xlsxwriter=3.0.3
  - xz=5.4.2
  - yaml=0.2.5
  - yapf=0.31.0
  - zeromq=4.3.4
  - zfp=0.5.5
  - zlib=1.2.13
  - zope=1.0
  - zope.interface=5.4.0
  - zstd=1.5.5
  - pip:
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - anyascii==0.3.2
    - anyio==3.5.0
    - applaunchservices==0.3.0
    - appnope==0.1.2
    - appscript==1.1.2
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - astroid==2.14.2
    - astropy==5.1
    - async-timeout==4.0.2
    - attrs==22.1.0
    - audioread==3.0.0
    - babel==2.11.0
    - bangla==0.0.2
    - bcrypt==3.2.0
    - beautifulsoup4==4.12.2
    - bitarray==2.5.1
    - bkcharts==0.2
    - black==0.0
    - bnnumerizer==0.0.2
    - bnunicodenormalizer==0.1.1
    - bokeh==2.4.3
    - boto3==1.24.28
    - botocore==1.27.59
    - bottleneck==1.3.5
    - brotlipy==0.7.0
    - cachetools==5.3.0
    - cffi==1.15.1
    - chardet==4.0.0
    - click==8.0.4
    - cloudpickle==2.2.1
    - clyent==1.2.2
    - colorama==0.4.6
    - colorcet==3.0.1
    - comm==0.1.2
    - constantly==15.1.0
    - contourpy==1.0.5
    - coqpit==0.0.17
    - cryptography==39.0.1
    - cython==0.29.28
    - cytoolz==0.12.0
    - daal4py==2021.4.0
    - dask==2023.4.1
    - datashader==0.14.4
    - datashape==0.5.4
    - dateparser==1.1.8
    - debugpy==1.5.1
    - dill==0.3.6
    - distributed==2023.4.1
    - docopt==0.6.2
    - docstring-to-markdown==0.11
    - docutils==0.18.1
    - einops==0.6.1
    - encodec==0.1.1
    - entrypoints==0.4
    - et-xmlfile==1.1.0
    - fastjsonschema==2.16.2
    - filelock==3.9.0
    - flake8==6.0.0
    - flask==2.2.2
    - freesound-python==1.1
    - frozenlist==1.3.3
    - fsspec==2023.4.0
    - funcy==2.0
    - fuzzywuzzy==0.18.0
    - g2pkk==0.1.2
    - gensim==4.3.0
    - gmpy2==2.1.2
    - google==3.0.0
    - google-api-core==2.11.0
    - google-api-python-client==2.86.0
    - google-auth==2.18.0
    - google-auth-httplib2==0.1.0
    - google-auth-oauthlib==1.0.0
    - google-pasta==0.2.0
    - googleapi==0.1.0
    - googleapis-common-protos==1.59.0
    - greenlet==2.0.1
    - gruut==2.2.3
    - gruut-ipa==0.13.0
    - gruut-lang-de==2.0.0
    - gruut-lang-en==2.0.0
    - gtts==2.3.2
    - h5py==3.7.0
    - holoviews==1.15.4
    - httplib2==0.22.0
    - huggingface-hub==0.14.1
    - hvplot==0.8.2
    - idna==3.4
    - imagecodecs==2021.8.26
    - imageio==2.26.0
    - imagesize==1.4.1
    - importlib-metadata==6.0.0
    - inflect==5.6.0
    - inflection==0.5.1
    - intake==0.6.8
    - ipykernel==6.19.2
    - ipython==8.12.0
    - ipywidgets==8.0.4
    - isodate==0.6.1
    - jamo==0.4.1
    - jedi==0.18.1
    - jieba==0.42.1
    - jinja2==3.1.2
    - joblib==1.1.1
    - jsonlines==1.2.0
    - jsonschema==4.17.3
    - jupyter==1.0.0
    - jupyter-client==8.1.0
    - jupyter-console==6.6.3
    - jupyter-core==5.3.0
    - jupyter-server==1.23.4
    - jupyterlab==3.5.3
    - jupyterlab-server==2.22.0
    - jupyterlab-widgets==3.0.5
    - keyring==23.13.1
    - kiwisolver==1.4.4
    - lazy-loader==0.2
    - lazy-object-proxy==1.6.0
    - levenshtein==0.21.0
    - librosa==0.10.0.post2
    - llvmlite==0.39.1
    - lmdb==1.4.1
    - locket==1.0.0
    - lxml==4.9.2
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.7.1
    - matplotlib-inline==0.1.6
    - mecab-python3==1.0.5
    - mistune==0.8.4
    - mkl-service==2.4.0
    - mpmath==1.2.1
    - msgpack==1.0.3
    - multidict==6.0.4
    - multipledispatch==0.6.0
    - mypy-extensions==0.4.3
    - nbclassic==0.5.5
    - nbclient==0.5.13
    - nbconvert==6.5.4
    - nbformat==5.7.0
    - nest-asyncio==1.5.6
    - networkx==2.8.4
    - notebook==6.5.4
    - notebook-shim==0.2.2
    - num2words==0.5.12
    - numba==0.56.4
    - numexpr==2.8.4
    - numpy==1.22.3
    - numpydoc==1.5.0
    - oauth2client==4.1.3
    - oauthlib==3.2.2
    - openai==0.27.6
    - openpyxl==3.0.10
    - packaging==23.0
    - pandas==1.5.3
    - panel==0.14.3
    - param==1.12.3
    - parsel==1.6.0
    - pathspec==0.10.3
    - pathvalidate==2.5.2
    - patsy==0.5.3
    - pep8==1.7.1
    - pillow==9.4.0
    - pip==23.0.1
    - platformdirs==2.5.2
    - plotly==5.9.0
    - pluggy==1.0.0
    - ply==3.11
    - pooch==1.6.0
    - prometheus-client==0.14.1
    - prompt-toolkit==3.0.36
    - protobuf==3.19.6
    - psutil==5.9.0
    - pycodestyle==2.10.0
    - pycosat==0.6.4
    - pyct==0.5.0
    - pycurl==7.45.1
    - pydispatcher==2.0.5
    - pydocstyle==6.3.0
    - pydub==0.25.1
    - pyerfa==2.0.0
    - pyflakes==3.0.1
    - pygments==2.15.1
    - pylint==2.16.2
    - pylint-venv==2.3.0
    - pynndescent==0.5.10
    - pyobjc-core==9.0
    - pyobjc-framework-cocoa==9.0
    - pyobjc-framework-coreservices==9.0
    - pyobjc-framework-fsevents==9.0
    - pyodbc==4.0.34
    - pyopenssl==23.0.0
    - pyparsing==3.0.9
    - pypinyin==0.49.0
    - pyqt5==5.15.7
    - pyqt5-sip==12.11.0
    - pyqtwebengine==5.15.4
    - pyrsistent==0.18.0
    - pysbd==0.3.4
    - pysocks==1.7.1
    - pytest==7.1.2
    - python-crfsuite==0.9.9
    - python-dotenv==1.0.0
    - python-levenshtein==0.21.0
    - python-lsp-black==1.2.1
    - python-lsp-server==1.7.2
    - python-snappy==0.6.1
    - pytoolconfig==1.2.5
    - pytz==2022.7
    - pywavelets==1.4.1
    - pyyaml==6.0
    - pyzmq==25.0.2
    - qstylizer==0.2.2
    - qtawesome==1.2.2
    - qtconsole==5.4.2
    - qtpy==2.2.0
    - queuelib==1.5.0
    - rapidfuzz==3.0.0
    - regex==2022.7.9
    - requests==2.29.0
    - requests-oauthlib==1.3.1
    - rope==1.7.0
    - rsa==4.9
    - rtree==1.0.1
    - ruamel-yaml-clib==0.2.6
    - ruamel-yaml-conda==0.17.21
    - s3transfer==0.6.0
    - scikit-image==0.19.3
    - scikit-learn==1.2.2
    - scikit-learn-intelex==2021.20220118.144251
    - scipy==1.7.3
    - scrapy==2.8.0
    - seaborn==0.12.2
    - setuptools==66.0.0
    - sip==6.7.9
    - smart-open==5.2.1
    - sniffio==1.2.0
    - soundfile==0.12.1
    - soupsieve==2.4
    - soxr==0.3.5
    - sphinx==5.0.2
    - spyder==5.4.3
    - spyder-kernels==2.4.3
    - sqlalchemy==1.4.39
    - sqlitedict==2.1.0
    - statsmodels==0.13.5
    - suno-bark==0.0.1a0
    - sympy==1.11.1
    - tables==3.7.0
    - tabulate==0.8.10
    - tbb==0.2
    - tenacity==8.2.2
    - tensorboardx==2.6
    - terminado==0.17.1
    - testpath==0.6.0
    - tinycss2==1.2.1
    - tokenizers==0.13.3
    - tomli==2.0.1
    - tomlkit==0.11.1
    - toolz==0.12.0
    - torch==2.0.1
    - torchaudio==2.0.2
    - tornado==6.2
    - tqdm==4.65.0
    - trainer==0.0.20
    - traitlets==5.7.1
    - transformers==4.29.1
    - tts==0.13.3
    - twisted==22.10.0
    - typing-extensions==4.5.0
    - tzlocal==5.0
    - ujson==5.4.0
    - umap-learn==0.5.1
    - unidic-lite==1.0.8
    - uritemplate==4.1.1
    - urllib3==1.26.15
    - watchdog==2.1.6
    - webencodings==0.5.1
    - websocket-client==0.58.0
    - werkzeug==2.2.3
    - whatthepatch==1.0.2
    - wheel==0.38.4
    - widgetsnbextension==4.0.5
    - wrapt==1.14.1
    - wurlitzer==3.0.2
    - xarray==2022.11.0
    - xlwings==0.29.1
    - yarl==1.9.2
    - youtube-dl==2021.12.17
    - zict==2.2.0
    - zipp==3.11.0
    - zope-interface==5.4.0
