llm_filter_prompt: >
  Can you tell me if this video title represents a video that would be appropriate for a 
  variety show that is meant to be uplifting and simulate nostalgic feelings? I want to 
  avoid controversial, misogynistic, and political content. You should be more lenient
  with channels from well known sources like NPR, PBS, and the BBC as well as late night
  talk shows.
  
  Make your best guess attempt and respond only with yes or no.

  The title is "{{ title }}" and the description is "{{ description }}"
  and the channel title is "{{ channel_title }}".

  Respond only with the following schema:
llm_filter_js:
  type: object
  properties:
    answer:
      type: string
      pattern: '^(?i)(yes|no)$'