name: Python application test with pip

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
        
    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10.11'
        # cache: 'pip' # caching pip dependencies
    - run: pip install -e .
    - name: Run tests
      run: |
        pytest tests/test*.py
